coretrix/hitrix

service/component/jwt/jwt.go, test/jwt_test.go
I kept the old function and created a new one for backward compatibility
and defined several helper functions to use on both of these functions
=> Added JWT verify function with payload

pkg/helper/array.go, pkg/helper/graphql.go
[WIP]
add function `GraphqlErr` that you can pass the path as array and message and generate error for you
add some simple helper function for slice in golang
=> add helper functions for graphql and some array functions

pkg/helper/array.go, pkg/helper/array_test.go, server.go
add helper functions for array subtract
=> add array helper function for subtract

go.mod, pkg/test/test.go, service/registry/orm_config.go
replace flushdb with flushall in tests to clear all redis and redis-search data
=> replace flushdb with flushall in tests

go.mod
=> migrate to new orm v1.2.13

example/entity/admin_user_entity.go, go.mod, service/component/authentication/authentication.go, service/registry/authentication.go, test/authentication_test.go
add logout from current session and from all sessions
=> refactor authentication service

README.md, example/config/my-app/config.yaml, example/entity/init.go, example/entity/sms_tracker_entity.go, go.mod, pkg/entity/sms_tracker_entity.go, pkg/helper/call.go, service/component/authentication/authentication.go, service/component/generator/generator.go, service/component/generator/mocks/generator.go, service/component/sms/gateway.go, service/component/sms/kavenegar_gateway.go, service/component/sms/log.go, service/component/sms/mocks/sms.go, service/component/sms/sender.go, service/component/sms/sinch_gateway.go, service/component/sms/twilio_gateway.go, service/registry/authentication.go, service/registry/generator.go, service/registry/mocks/generator.go, service/registry/mocks/sms.go, service/registry/sms.go, service/service.go, test/authentication_test.go, test/generator_test.go, test/sms_test.go
add otp authentication and sms service
please don't merge just for review
=> [WIP] add otp-sms

service/registry/authentication.go, test/authentication_test.go
fix env for auth service
fix problem with casting env
=> fix env for auth service

README.md, example/entity/api_logger_entity.go, example/entity/sms_tracker_entity.go, example/server.go, go.mod, pkg/test/test.go, server.go
=> migrate to new version of orm

pkg/test/test.go
add header to test graphql pkg
=> add header to test graphql pkg

README.md, example/config/hitrix.yaml, go.mod, pkg/test/test.go, service/component/amazon/mocks/s3.go, service/component/amazon/storage/s3.go, service/registry/mocks/s3.go, service/service.go
=> feature(graphql-test): add support for testing multipart mutations

go.mod
=> update orm to new version

pkg/test/test.go
=> make truncating tables faster

go.mod, pkg/controller/dev_panel_controller.go, pkg/model/account/login_dev.go
Refactored dev panel user creation
=> Refactored dev panel user creation

pkg/test/graphql-parser/query.go
increase depth value for making graphql list queries
=> increase depth value for making Graphql list queries

go.mod, pkg/helper/auth.go, pkg/helper/call.go, service/component/sms/gateway.go, service/component/sms/kavenegar_gateway.go, service/component/sms/sender.go, service/component/sms/sinch_gateway.go, service/component/sms/twilio_gateway.go, service/registry/sms.go
@moeen  
I have added Twilio verify functionality into the SMS service.
This is the first attempt to get an idea. Please check and see if we can continue.
=> Verify service for sms gateway

README.md, service/component/sms/mocks/sms.go, service/component/sms/sender.go, service/component/sms/twilio_gateway.go
@moeen 
1. I missed one function in the interface that I added in this PR.
2. In this function, we only check the verification code. Do we need to write a log with the logger with the type of SMSTrackerTypeSMS?
=> adding missed function in ISender interface

service/component/sms/twilio_gateway.go
=> bug fix: using twilio url from config

service/component/file_extractor/file_extractor.go, service/component/localizer/localizer.go, service/component/localizer/poeditor.go, service/component/localizer/source.go, service/registry/file_extractor.go, service/registry/localizer.go, service/service.go
=> localizer and extractor service added

service/component/sms/twilio_gateway.go, service/registry/sms.go
@a-shumanski @moeen Please check and review. Bug on Verify service fixed.
=> bug fix on checking api response

README.md
=> update readme: localizer + extractor service

service/component/sms/twilio_gateway.go
@a-shumanski added a check on the response body of Twilio API.
=> improve verify response with struct status

README.md, service/component/app/app_definition.go
@a-shumanski Please check and approve.
=> adding dev mode const and check function

README.md
@a-shumanski just a simple typo fix in the readme file.
=> fix a typo in readmefile

README.md, go.mod, service/component/pdf/mocks/pdf.go, service/component/pdf/pdf.go, service/registry/pdf.go, service/service.go
@a-shumanski pdf service added. Check it, please.
=> pdf service + docs

gin.go, service/component/crud/list.go, service/component/mail/mandrill_sender.go
- Add Mandrill templating merge_language `Handlebars` by default
- Add SearchOR to crud service
- Fix `GenerateListMysqlQuery()` in crud service
=> Mandrill fix + SearchOR in CRUD Service + fix in CRUD Service

gin.go, pkg/helper/validator.go, service/component/generator/generator.go, service/component/generator/mocks/generator.go, service/component/generator/simple.go
Generators: 
- Added `RandomPasswordGenerator(passwordLength int)`
- Added `RandomPINCodeGenerator(codeLength int)`
Refactored Hitrix Validator so that it is automatically injected into the binding. Providing the custom validators AND the translations automatically.
- Added new custom validation rule `password_strength`
=> Generators and Custom Validations

service/component/crud/const.go, service/component/crud/list.go, service/component/localize/localizer.go, service/registry/localize.go
=> improve crud service

docs/docs/guide/services/elorus.md, service/component/elorus/elorus.go, service/component/elorus/elorus_provider.go
Invoice list + download invoice
=> Invoice list + download invoice

docs/docs/.vuepress/config/sidebar.js
=> add elorus to side bar

service/registry/orm_config.go
If you add any query string to mysql config in test mode, it crashed.
This PR fixes it.
=> fix rare bug in tests

service/component/elorus/elorus.go
add is client to create contact request
=> add is client to request

service/component/elorus/elorus.go
=> check elorus response code

pkg/controller/dev_panel_controller.go, pkg/middleware/router.go
add endpoint to get env values
=> add endpoint to get env values

service/component/feature_flag/feature_flag_with_cache.go, service/registry/feature_flag.go, test/feature_flag_test.go
=> feature flag with cache

pkg/queue/consumer.go, registry.go, server.go, service/component/app/app_definition.go
=> wait for consumers to finish 
